//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telephone
    {
        public string ID { get; set; }
        public string Familia { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public string Debt_ID { get; set; }
    
        public virtual Debt Debt { get; set; }
    }
}
